if(NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE "Release")
endif()

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
        set(libcpp_hardening _LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_DEBUG)
    else()
        set(libcpp_hardening _LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_FAST)
endif()

set(VICI_DIR "${CMAKE_CURRENT_LIST_DIR}/../../")
file(REAL_PATH "${VICI_DIR}" VICI_DIR)

set(CMAKE_C_COMPILER "${VICI_DIR}/third_party/clang/clang-cl.exe")
set(CMAKE_CXX_COMPILER ${CMAKE_C_COMPILER})

set(LIBCXX_PATH "${VICI_DIR}/third_party/libcxx")
set(FLAGS "-v -I\"${LIBCXX_PATH}/include\" -I\"${LIBCXX_PATH}/include.19\" -fuse-ld=lld /clang:-fexceptions /EHsc -D${libcpp_hardening} /Zc:dllexportInlines- -msse2")

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${FLAGS}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${FLAGS}")

set(LIBCXX_LINK_FLAGS "-libpath:\"${LIBCXX_PATH}/${CMAKE_BUILD_TYPE}/lib\" libc++.dll.lib")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${LIBCXX_LINK_FLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} ${LIBCXX_LINK_FLAGS}")
set(CMAKE_STATIC_LINKER_FLAGS "${CMAKE_STATIC_LINKER_FLAGS} ${LIBCXX_LINK_FLAGS}")

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_C_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_C_EXTENSIONS OFF)
